import { CycleType } from '@prisma/client';

export const usersData = [
  { name: '김민준', password: 'password123', email: 'kimminjun@example.com' },
  { name: '이서연', password: 'password123', email: 'leeseoyeon@example.com' },
  { name: '박지훈', password: 'password123', email: 'parkjihoon@example.com' },
  { name: '최은서', password: 'password123', email: 'choieunseo@example.com' },
  { name: '정우진', password: 'password123', email: 'jungwoojin@example.com' },
  { name: '한지아', password: 'password123', email: 'hanjia@example.com' },
  { name: '강현우', password: 'password123', email: 'kanghyunwoo@example.com' },
  { name: '송윤아', password: 'password123', email: 'songyuna@example.com' },
  { name: '윤도현', password: 'password123', email: 'yundohyeon@example.com' },
  { name: '임수민', password: 'password123', email: 'imsumin@example.com' },
];

export const diaryData = [
  {
    user_id: 1,
    title: '기분 좋은 아침',
    content: '오늘은 날씨가 맑아서 기분이 좋았다.',
    memory: '행복했던 기억',
    emotion: '기쁨',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 2,
    title: '새로운 프로젝트 시작',
    content: '오랫동안 준비한 프로젝트를 드디어 시작했다. 잘 되길 바란다.',
    memory: null,
    emotion: '기대',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 3,
    title: '주말 나들이',
    content: '가족들과 함께 공원에 갔다. 즐거운 시간을 보냈다.',
    memory: '공원에서 찍은 사진',
    emotion: '행복',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 4,
    title: '힘든 하루',
    content: '업무가 많아 스트레스를 받았다. 빨리 쉬고 싶다.',
    memory: null,
    emotion: '피곤',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 5,
    title: '새로운 취미',
    content: '요즘 베이킹을 배우기 시작했다. 첫 작품은 실패했지만 재미있다.',
    memory: '첫 베이킹 사진',
    emotion: '흥미',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 1,
    title: '친구와 저녁 식사',
    content: '오랜만에 친구를 만나 맛있는 음식을 먹었다.',
    memory: '맛집 탐방',
    emotion: '즐거움',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 6,
    title: '독서의 시간',
    content: '조용한 카페에서 책을 읽으며 여유를 즐겼다.',
    memory: '책갈피',
    emotion: '평온',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 7,
    title: '운동 시작',
    content: '헬스장 등록 후 첫 운동을 했다. 몸이 뻐근하지만 상쾌하다.',
    memory: null,
    emotion: '개운',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 8,
    title: '반려식물 성장',
    content: '키우는 식물이 무럭무럭 자라고 있다. 뿌듯하다.',
    memory: '식물 성장 일지',
    emotion: '뿌듯',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    user_id: 9,
    title: '영화 감상',
    content: '최신 영화를 봤다. 감동적이었다.',
    memory: '영화 티켓',
    emotion: '감동',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const emotionData = [
  { user_id: 1, type: '행복', created_at: new Date() },
  { user_id: 2, type: '기대', created_at: new Date() },
  { user_id: 3, type: '뿌듯', created_at: new Date() },
  { user_id: 4, type: '피곤', created_at: new Date() },
  { user_id: 5, type: '흥미', created_at: new Date() },
  { user_id: 6, type: '평온', created_at: new Date() },
  { user_id: 7, type: '개운', created_at: new Date() },
  { user_id: 8, type: '기쁨', created_at: new Date() },
  { user_id: 9, type: '감동', created_at: new Date() },
  { user_id: 10, type: '즐거움', created_at: new Date() },
];

export const plantData = [
  {
    user_id: 1,
    variety: '몬스테라',
    name: '몬',
    cycle_type: 'BIWEEKLY',
    cycle_value: '14',
    purchase_date: new Date(),
    purchase_location: '온라인',
    memo: '새 잎이 나고 있어요.',
    img_url: 'https://example.com/plant1.jpg',
  },
  {
    user_id: 2,
    variety: '산세베리아',
    name: '산이',
    cycle_type: 'MONTHLY',
    cycle_value: '30',
    purchase_date: new Date(),
    purchase_location: '화훼단지',
    memo: null,
    img_url: 'https://example.com/plant2.jpg',
  },
  {
    user_id: 3,
    variety: '스투키',
    name: '스투키',
    cycle_type: 'WEEKLY',
    cycle_value: '7',
    purchase_date: new Date(),
    purchase_location: '마트',
    memo: '건조하게 키우는 중',
    img_url: 'https://example.com/plant3.jpg',
  },
  {
    user_id: 4,
    variety: '바질',
    name: '바지리',
    cycle_type: 'WEEKLY',
    cycle_value: '7',
    purchase_date: new Date(),
    purchase_location: '다이소',
    memo: '햇빛을 좋아해요.',
    img_url: 'https://example.com/plant4.jpg',
  },
  {
    user_id: 5,
    variety: '로즈마리',
    name: '마리',
    cycle_type: 'TRIWEEKLY',
    cycle_value: '21',
    purchase_date: new Date(),
    purchase_location: '화원',
    memo: '향이 좋아요',
    img_url: 'https://example.com/plant5.jpg',
  },
  {
    user_id: 6,
    variety: '라벤더',
    name: '라벤',
    cycle_type: 'TRIWEEKLY',
    cycle_value: '21',
    purchase_date: new Date(),
    purchase_location: '마트',
    memo: null,
    img_url: 'https://example.com/plant6.jpg',
  },
  {
    user_id: 7,
    variety: '스킨답서스',
    name: '스킨이',
    cycle_type: 'BIWEEKLY',
    cycle_value: '14',
    purchase_date: new Date(),
    purchase_location: '온라인',
    memo: '물꽂이 중',
    img_url: 'https://example.com/plant7.jpg',
  },
  {
    user_id: 8,
    variety: '고무나무',
    name: '고무고무',
    cycle_type: 'MONTHLY',
    cycle_value: '30',
    purchase_date: new Date(),
    purchase_location: '화훼단지',
    memo: '새 잎이 쑥쑥',
    img_url: 'https://example.com/plant8.jpg',
  },
  {
    user_id: 9,
    variety: '알로카시아',
    name: '알로',
    cycle_type: 'WEEKLY',
    cycle_value: '7',
    purchase_date: new Date(),
    purchase_location: '마트',
    memo: '물을 자주 주세요',
    img_url: 'https://example.com/plant9.jpg',
  },
  {
    user_id: 10,
    variety: '피어리스',
    name: '피리',
    cycle_type: 'BIWEEKLY',
    cycle_value: '14',
    purchase_date: new Date(),
    purchase_location: '온라인',
    memo: '가지치기 필요',
    img_url: 'https://example.com/plant10.jpg',
  },
];

export const taskLogData = [
  { plant_id: 1, completion_date: new Date(), type: '물주기' },
  { plant_id: 2, completion_date: new Date(), type: '분갈이' },
  { plant_id: 3, completion_date: new Date(), type: '영양제 주기' },
  { plant_id: 4, completion_date: new Date(), type: '물주기' },
  { plant_id: 5, completion_date: new Date(), type: '가지치기' },
  { plant_id: 6, completion_date: new Date(), type: '물주기' },
  { plant_id: 7, completion_date: new Date(), type: '잎 닦아주기' },
  { plant_id: 8, completion_date: new Date(), type: '물주기' },
  { plant_id: 9, completion_date: new Date(), type: '분무하기' },
  { plant_id: 10, completion_date: new Date(), type: '물주기' },
];

export const postData = [
  {
    user_id: 1,
    title: '첫 번째 게시글',
    content: '안녕하세요! NestJS와 Prisma로 개발 중입니다.',
    likes: 3,
    createdAt: new Date(),
  },
  {
    user_id: 2,
    title: '새로운 기술 스택',
    content: 'React와 Next.js를 공부하고 있는데 정말 재미있네요.',
    likes: 5,
    createdAt: new Date(),
  },
  {
    user_id: 3,
    title: '맛집 추천',
    content: '강남에 있는 파스타 맛집을 발견했어요!',
    likes: 12,
    createdAt: new Date(),
  },
  {
    user_id: 4,
    title: '운동 챌린지 시작',
    content: '오늘부터 30일간 매일 1시간씩 운동하기!',
    likes: 8,
    createdAt: new Date(),
  },
  {
    user_id: 5,
    title: '고양이 사진 자랑',
    content: '우리 집 귀여운 고양이 사진 올립니다!',
    likes: 25,
    createdAt: new Date(),
  },
  {
    user_id: 6,
    title: '개발자 취업 준비',
    content: '면접을 앞두고 코딩 테스트 연습 중입니다.',
    likes: 10,
    createdAt: new Date(),
  },
  {
    user_id: 7,
    title: '좋은 글귀',
    content: '포기하지 않으면 언젠가 빛을 볼 수 있습니다.',
    likes: 7,
    createdAt: new Date(),
  },
  {
    user_id: 8,
    title: '반려견과 산책',
    content: '오늘 날씨가 좋아서 반려견과 함께 산책했어요.',
    likes: 15,
    createdAt: new Date(),
  },
  {
    user_id: 9,
    title: '영화 후기',
    content: "최근에 본 '인셉션'이라는 영화가 정말 인상 깊었어요.",
    likes: 9,
    createdAt: new Date(),
  },
  {
    user_id: 10,
    title: '여행 계획',
    content: '이번 여름휴가 때 제주도에 갈 계획입니다.',
    likes: 20,
    createdAt: new Date(),
  },
];

export const commentData = [
  { post_id: 1, user_id: 2, content: '응원합니다!', createdAt: new Date() },
  { post_id: 1, user_id: 3, content: '화이팅!', createdAt: new Date() },
  { post_id: 2, user_id: 1, content: '멋진데요!', createdAt: new Date() },
  { post_id: 3, user_id: 4, content: '정보 감사합니다!', createdAt: new Date() },
  { post_id: 4, user_id: 5, content: '저도 함께해요!', createdAt: new Date() },
  { post_id: 5, user_id: 6, content: '너무 귀여워요!', createdAt: new Date() },
  { post_id: 6, user_id: 7, content: '잘 될 거예요!', createdAt: new Date() },
  { post_id: 7, user_id: 8, content: '힘이 되는 글이네요.', createdAt: new Date() },
  { post_id: 8, user_id: 9, content: '강아지 너무 예뻐요!', createdAt: new Date() },
  { post_id: 9, user_id: 10, content: '명작이죠!', createdAt: new Date() },
];

export const likesData = [
  { user_id: 1, post_id: 2 },
  { user_id: 2, post_id: 1 },
  { user_id: 3, post_id: 4 },
  { user_id: 4, post_id: 3 },
  { user_id: 5, post_id: 6 },
  { user_id: 6, post_id: 5 },
  { user_id: 7, post_id: 8 },
  { user_id: 8, post_id: 7 },
  { user_id: 9, post_id: 10 },
  { user_id: 10, post_id: 9 },
];

export const postImgData = [
  { post_id: 1, img_url: 'https://example.com/post1-img1.jpg' },
  { post_id: 2, img_url: 'https://example.com/post2-img1.jpg' },
  { post_id: 3, img_url: 'https://example.com/post3-img1.jpg' },
  { post_id: 4, img_url: 'https://example.com/post4-img1.jpg' },
  { post_id: 5, img_url: 'https://example.com/post5-img1.jpg' },
  { post_id: 6, img_url: 'https://example.com/post6-img1.jpg' },
  { post_id: 7, img_url: 'https://example.com/post7-img1.jpg' },
  { post_id: 8, img_url: 'https://example.com/post8-img1.jpg' },
  { post_id: 9, img_url: 'https://example.com/post9-img1.jpg' },
  { post_id: 10, img_url: 'https://example.com/post10-img1.jpg' },
];

export const diaryImgData = [
  { diary_id: 1, img_url: 'https://example.com/diary1-img1.jpg' },
  { diary_id: 2, img_url: 'https://example.com/diary2-img1.jpg' },
  { diary_id: 3, img_url: 'https://example.com/diary3-img1.jpg' },
  { diary_id: 4, img_url: 'https://example.com/diary4-img1.jpg' },
  { diary_id: 5, img_url: 'https://example.com/diary5-img1.jpg' },
  { diary_id: 6, img_url: 'https://example.com/diary6-img1.jpg' },
  { diary_id: 7, img_url: 'https://example.com/diary7-img1.jpg' },
  { diary_id: 8, img_url: 'https://example.com/diary8-img1.jpg' },
  { diary_id: 9, img_url: 'https://example.com/diary9-img1.jpg' },
  { diary_id: 10, img_url: 'https://example.com/diary10-img1.jpg' },
];
